% plot CTD data as a set of subplots with the physical data on top
% and anomaly graphs on the bottom in which the mean of each quantity is
% subtracted from the entire set i.e.: 
% temperature-mean(temperature),...etc.

for j = 1:1   
    
    id = theta_flag(:,j) == 0;
    grid_plotter(range(id,j),depth(id,j),theta(id,j),j,MeanTheta,output_path,...
            'XName','range (km)',...
            'YName','depth (m)',...
            'ZName','Theta',...
            'ZUnits','C^o',...
            'ZvalueFill','off',...
            'Smoothing','off',...
            'SmoothingSize',15,...
            'Contours','on',...
            'ContourLevels',[3.25 3.5 4 5],...
            'Scatter','on');
        
     close gcf
     clear hl ax1 ax2

    id = salinity_flag(:,j) == 0;
    grid_plotter(range(id,j),depth(id,j),salinity(id,j),j,MeanSalinity,output_path,...
            'XName','range (km)',...
            'YName','depth (m)',...
            'ZName','Salinity',...
            'ZUnits','PSU',...
            'ZvalueFill','off',...
            'Smoothing','off',...
            'SmoothingSize',10,...
            'Contours','on',...
            'ContourLevels',[34.6 34.7 34.8 34.85],...
            'Scatter','on');
        
     close gcf
     clear hl ax1 ax2

    id = sigma_flag(:,j) == 0;
    grid_plotter(range(id,j),depth(id,j),sigma(id,j),j,MeanSigma-1000,output_path,...
            'XName','range (km)',...
            'YName','depth (m)',...
            'ZName','Density',...
            'ZUnits','kg/m^3',...
            'ZvalueFill','off',...
            'Smoothing','off',...
            'SmoothingSize',5,...
            'Contours','on',...
            'ContourLevels',[27.20 27.5 27.7 27.74],...
            'Scatter','on');

     close gcf
     clear hl ax1 ax2 
end





